# Generated by Django 3.1.7 on 2021-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_convoy_id', models.IntegerField()),
                ('truck_convoy_position', models.IntegerField()),
                ('tour_id', models.IntegerField()),
                ('start_time', models.DateTimeField(verbose_name='started driving')),
                ('driving_time', models.IntegerField()),
                ('arrival_time', models.DateTimeField(verbose_name='arrival driving')),
                ('street_id', models.IntegerField()),
                ('in_convoy', models.BooleanField(default=False)),
                ('driving', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=True)),
                ('in_depot', models.BooleanField(default=True)),
                ('on_tour', models.BooleanField(default=False)),
            ],
        ),
    ]
