# Generated by Django 3.1.7 on 2021-06-08 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEntity',
            fields=[
                ('truckId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('length', models.PositiveIntegerField(default=18.0)),
                ('currentRouteSection', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currentSpeed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)])),
                ('currentAcceleration', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(2.5)])),
                ('targetRouteSection', models.FloatField(default=20000.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('targetSpeed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)])),
                ('polling', models.BooleanField(default=False)),
                ('broken', models.BooleanField(default=False)),
                ('convoyLeader', models.PositiveIntegerField()),
                ('convoyPosition', models.PositiveIntegerField()),
            ],
        ),
    ]
