# Generated by Django 3.1.7 on 2021-06-15 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEntity',
            fields=[
                ('id', models.PositiveIntegerField(default=151, primary_key=True, serialize=False)),
                ('length', models.FloatField(default=18.0)),
                ('distance', models.FloatField(default=0.5)),
                ('currentDistance', models.FloatField(default=0.0)),
                ('currentRouteSection', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currentSpeed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)])),
                ('acceleration', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(2.5)])),
                ('targetRouteSection', models.FloatField(default=2000.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('targetSpeed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)])),
                ('leadingTruckAddress', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('frontTruckAddress', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('backTruckAddress', models.TextField(blank=True, default=None, max_length=50, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('polling', models.BooleanField(default=False)),
                ('broken', models.BooleanField(default=False)),
            ],
        ),
    ]
