# Generated by Django 3.1.7 on 2021-06-08 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckentity',
            name='truckId',
        ),
        migrations.AddField(
            model_name='truckentity',
            name='id',
            field=models.PositiveIntegerField(default=151, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truckentity',
            name='address',
            field=models.CharField(default='127.0.0.1:1200', max_length=50),
        ),
        migrations.AlterField(
            model_name='truckentity',
            name='convoyLeader',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truckentity',
            name='convoyPosition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truckentity',
            name='length',
            field=models.FloatField(default=18.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
