# Generated by Django 3.1.7 on 2021-06-15 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckentity',
            name='currentSpeed',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(22.22222222222222)]),
        ),
        migrations.AlterField(
            model_name='truckentity',
            name='targetSpeed',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(22.22222222222222)]),
        ),
    ]
