# Generated by Django 3.1.7 on 2021-06-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20210609_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckentity',
            old_name='currentAcceleration',
            new_name='acceleration',
        ),
    ]
