# Generated by Django 3.1.7 on 2021-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20210608_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckentity',
            name='address',
            field=models.CharField(default='127.0.0.1:7000', max_length=50),
        ),
    ]
