# Generated by Django 3.1.7 on 2021-06-09 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_auto_20210609_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckentity',
            name='targetRouteSection',
            field=models.FloatField(default=2000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
