# Generated by Django 3.1.7 on 2021-06-23 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_truckentity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckentity',
            name='targetRouteSection',
            field=models.FloatField(default=20000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
